### ISSUE TITLE
v0.21.3 ->Sometimes i can't move my pnj token if he is superimposed (partially or not) on another token

### ISSUE THREAD

**Issue by MaxPantsDaddy** [Amphaal/rpgrpz#18] opened 2020-04-08 15:05 UTC
It's happens sometimes if i place my pnj token under or partially under another token

**Comment by gg-vara** [comment] 2020-04-09 12:34
I cannot reproduce this issue. Can you give me a specific use case of when this happens ?

**Comment by gg-vara** [comment] 2020-04-09 20:19
Apparently fixed with https://github.com/Amphaal/rpgrpz/commit/693925110e8cc8f3f2354322d19524ab39570873.

**Closed as completed by gg-vara** 2020-04-09 20:19 UTC
Labels: question
