### ISSUE TITLE
Import PNG Files cause Launch issues

### ISSUE THREAD

**Issue by Syler57** [Amphaal/rpgrpz#48] opened 2020-06-17 00:49 UTC
When i upload a png file it goes to the download folder and not in objects like requested. 
In download he's grey and cannot be selected. If you leave application and try to relaunch it, nothing happen. 
![Pied estale](https://user-images.githubusercontent.com/62910686/84842190-c9e95c00-b044-11ea-82ba-593125baa136.png)

**Comment by gg-vara** [comment] 2020-06-18 11:13
Caused by a bug, which was fixed in https://github.com/Amphaal/rpgrpz/commit/ad576308240f2bf8717f6256b79ee261486e157a, but artefacts still remains in the resources database. Since we have few users for now, manual database fix will be enough. Please get in touch with me so I can do it for you.

**Closed as completed by gg-vara** 2020-06-18 11:13 UTC
